### ISSUE TITLE
The struct macro_def has to be 17 bytes in my MinGW-W64 32bit GCC compiler

### ISSUE THREAD

**Issue by asmwarrior** [glampert/parse-utils#2]
I can only build the test code by this patch:

```
diff --git a/preprocessor.hpp b/preprocessor.hpp
index 965987e..442a5db 100644
--- a/preprocessor.hpp
+++ b/preprocessor.hpp
@@ -268,7 +268,7 @@ private:
 
     // We don't need more than the above specified bit widths, so packing the structure
     // helps save memory and allows fitting more macro_defs into each cache line.
-    static_assert(sizeof(macro_def) == 16, "Wrong size for macro_def struct!");
+    static_assert(sizeof(macro_def) == 17, "Wrong size for macro_def struct!");
 
     // Constants generated with hash_string() using the corresponding text string.
     static constexpr std::uint32_t builtin_macro_file    = 0x07215FFC; // __FILE__

```

I'm using such command:
`g++.exe -Wshadow -Weffc++ -Wall -std=c++11 -fexceptions -pedantic -g -I..\..\ -c test_eval_macros.cpp -o obj\Debug\tests\preprocessor\test_eval_macros.o`

The GCC I'm using is: MinGW-W64's i686-5.4.0-release-posix-dwarf-rt_v5-rev0, which is a 32bit GCC compiler for Windows. 
Thanks.

**Comment by glampert** [comment]
Yup, it's the bools in the bitfield that should be uints instead. Clang/gcc "make it work", but they are not correct. Will fix it, thanks for the heads up!

**Comment by glampert** [comment]
Fixed with https://github.com/glampert/parse-utils/commit/7062b774b2cada85da60ce28bf0b0663087b8c9f
